apiVersion: v1
kind: PersistentVolume
metadata:
  name: dhcp-flow-backend-pv
  namespace: dhcp-flow
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dhcp-flow"
  storageClassName: standard 