apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dhcp-flow-backend-pvc
  namespace: dhcp-flow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 