services:
  frontend:
    container_name: dhcp-flow-frontend
    image: umairsh/dhcp-flow-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    network_mode: "host"
    restart: unless-stopped

  backend:
    container_name: dhcp-flow-backend
    image: umairsh/dhcp-flow-backend
    ports:
      - "8080:8080"
    volumes:
      - dhcp-flow-backend-data:/app/data
    network_mode: "host"
    restart: unless-stopped

volumes:
  dhcp-flow-backend-data:
    name: dhcp-flow-backend-data
    driver: local

networks:
  host:
    external: true 