apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp-flow-backend
  namespace: dhcp-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcp-flow-backend
  template:
    metadata:
      labels:
        app: dhcp-flow-backend
    spec:
      containers:
      - name: dhcp-flow-backend
        image: dhcp-flow-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: backend-data
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: backend-data
        persistentVolumeClaim:
          claimName: dhcp-flow-backend-pvc 