apiVersion: v1
kind: Service
metadata:
  name: dhcp-flow-backend
  namespace: dhcp-flow
spec:
  selector:
    app: dhcp-flow-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 