apiVersion: v1
kind: Service
metadata:
  name: dhcp-flow-frontend
  namespace: dhcp-flow
spec:
  selector:
    app: dhcp-flow-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP 